experiment_name: seismic_training
train_augmentations: true
val_augmentations: true
training:
  batch_size: 1024
  num_workers: 16
  epochs: 2
  optimizer:
    name: Adam
    params:
      lr: 0.001
model:
  name: PhaseNet
augmentations: {}
dataset:
  name: BohemiaSaxony
  component_orders: ZNE
  dimension_orders: null
  sampling_rate: 100
