experiment_name: seismic_training
train_augmentations: true
val_augmentations: true
training:
  batch_size: 1024
  num_workers: 16
  epochs: 2
  optimizer:
    name: Adam
    params:
      lr: 0.001
model:
  name: PhaseNet
augmentations:
  augmentations:
  - _target_: seisbench.generate.WindowAroundSample
    samples_before: 3000
    windowlen: 6000
    selection: random
    strategy: variable
    enabled: true
  - _target_: seisbench.generate.RandomWindow
    windowlen: 3001
    strategy: pad
    enabled: true
  - _target_: seisbench.generate.Normalize
    demean_axis: -1
    amp_norm_axis: -1
    amp_norm_type: peak
    enabled: true
  - _target_: seisbench.generate.ChangeDtype
    dtype: np.float32
    enabled: true
  - _target_: seisbench.generate.ProbabilisticLabeller
    sigma: 30
    dim: 0
    enabled: true
dataset:
  name: BohemiaSaxony
  component_orders: ZNE
  dimension_orders: null
  sampling_rate: 100
lr: 0.001
sigma: 20
sample_boundaries:
- null
- null
optimizer_params:
  lr: 0.001
