experiment_name: seismic_training
model:
  name: PhaseNet
augmentations:
  window_default:
    samples_before: 3000
    windowlen: 6000
    selection: random
    strategy: variable
  random_window_default:
    windowlen: 3001
    strategy: pad
  normalize_default:
    demean_axis: -1
    amp_norm_axis: -1
    amp_norm_type: peak
  prob_labeller_default:
    sigma: 30
    dim: 0
    shape: gaussian
dataset:
  name: BohemiaSaxony
  component_orders: ZNE
  dimension_orders: null
  sampling_rate: 100
training:
  epochs: 1
  batch_size: 1024
  lr: 0.001
  optimizer: Adam
  num_workers: 16
